### ISSUE TITLE
lightweight_openpose video error

### ISSUE THREAD

**Issue by AndrewBarfield** [opencv-ai/oak-model-samples#6]
Ubuntu 20.10
Python 3.8
DepthAI 0.0.2.1+87247bfb645027a30c68191d88fe1b69b70e39ac

Looks like the video is broken. Error is: "moov atom not found".
The sample runs when using only the camera.

```
~/Repositories/oak-model-samples/lightweight_openpose
$ pip3 install wheel && python3 setup.py bdist_wheel && rm -R build/ *.egg-info
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wheel in /home/drew/.local/lib/python3.8/site-packages (0.36.2)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/lightweight_openpose
copying lightweight_openpose/utils.py -> build/lib/lightweight_openpose
copying lightweight_openpose/model.py -> build/lib/lightweight_openpose
copying lightweight_openpose/__init__.py -> build/lib/lightweight_openpose
creating build/lib/oak_inference_utils
copying oak_inference_utils/inference.py -> build/lib/oak_inference_utils
copying oak_inference_utils/args_parser.py -> build/lib/oak_inference_utils
copying oak_inference_utils/base_model.py -> build/lib/oak_inference_utils
copying oak_inference_utils/__init__.py -> build/lib/oak_inference_utils
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/oak_inference_utils
copying build/lib/oak_inference_utils/inference.py -> build/bdist.linux-x86_64/wheel/oak_inference_utils
copying build/lib/oak_inference_utils/args_parser.py -> build/bdist.linux-x86_64/wheel/oak_inference_utils
copying build/lib/oak_inference_utils/base_model.py -> build/bdist.linux-x86_64/wheel/oak_inference_utils
copying build/lib/oak_inference_utils/__init__.py -> build/bdist.linux-x86_64/wheel/oak_inference_utils
creating build/bdist.linux-x86_64/wheel/lightweight_openpose
copying build/lib/lightweight_openpose/utils.py -> build/bdist.linux-x86_64/wheel/lightweight_openpose
copying build/lib/lightweight_openpose/model.py -> build/bdist.linux-x86_64/wheel/lightweight_openpose
copying build/lib/lightweight_openpose/__init__.py -> build/bdist.linux-x86_64/wheel/lightweight_openpose
running install_egg_info
running egg_info
creating lightweight_openpose.egg-info
writing lightweight_openpose.egg-info/PKG-INFO
writing dependency_links to lightweight_openpose.egg-info/dependency_links.txt
writing requirements to lightweight_openpose.egg-info/requires.txt
writing top-level names to lightweight_openpose.egg-info/top_level.txt
writing manifest file 'lightweight_openpose.egg-info/SOURCES.txt'
reading manifest file 'lightweight_openpose.egg-info/SOURCES.txt'
writing manifest file 'lightweight_openpose.egg-info/SOURCES.txt'
Copying lightweight_openpose.egg-info to build/bdist.linux-x86_64/wheel/lightweight_openpose-0.2.0-py3.8.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/lightweight_openpose-0.2.0.dist-info/WHEEL
creating 'dist/lightweight_openpose-0.2.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'lightweight_openpose/__init__.py'
adding 'lightweight_openpose/model.py'
adding 'lightweight_openpose/utils.py'
adding 'oak_inference_utils/__init__.py'
adding 'oak_inference_utils/args_parser.py'
adding 'oak_inference_utils/base_model.py'
adding 'oak_inference_utils/inference.py'
adding 'lightweight_openpose-0.2.0.dist-info/LICENSE'
adding 'lightweight_openpose-0.2.0.dist-info/METADATA'
adding 'lightweight_openpose-0.2.0.dist-info/WHEEL'
adding 'lightweight_openpose-0.2.0.dist-info/top_level.txt'
adding 'lightweight_openpose-0.2.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel

~/Repositories/oak-model-samples/lightweight_openpose
$ pip3 install dist/*.whl -f https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/depthai/ && rm -R dist/
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/depthai/
Processing ./dist/lightweight_openpose-0.2.0-py3-none-any.whl
Collecting modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip
  Using cached https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: depthai==0.0.2.1+87247bfb645027a30c68191d88fe1b69b70e39ac in /home/drew/.local/lib/python3.8/site-packages (from lightweight-openpose==0.2.0) (0.0.2.1+87247bfb645027a30c68191d88fe1b69b70e39ac)
Requirement already satisfied: pydantic==1.5.1 in /home/drew/.local/lib/python3.8/site-packages (from modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (1.5.1)
Requirement already satisfied: loguru==0.5.1 in /home/drew/.local/lib/python3.8/site-packages (from modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (0.5.1)
Requirement already satisfied: numpy>=1.16.4 in /home/drew/.local/lib/python3.8/site-packages (from modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (1.17.5)
Requirement already satisfied: Pillow==7.1.2 in /home/drew/.local/lib/python3.8/site-packages (from modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (7.1.2)
Requirement already satisfied: imageio==2.9.0 in /home/drew/.local/lib/python3.8/site-packages (from modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (2.9.0)
Requirement already satisfied: opencv-python<5.0,>=4.2.0.34 in /home/drew/.local/lib/python3.8/site-packages (from modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (4.5.1.48)
Requirement already satisfied: sk-video==1.1.10 in /home/drew/.local/lib/python3.8/site-packages (from modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (1.1.10)
Requirement already satisfied: pycocotools==2.0.2 in /home/drew/.local/lib/python3.8/site-packages (from modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (2.0.2)
Requirement already satisfied: matplotlib>=2.1.0 in /usr/lib/python3/dist-packages (from pycocotools==2.0.2->modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (3.3.0)
Requirement already satisfied: setuptools>=18.0 in /home/drew/.local/lib/python3.8/site-packages (from pycocotools==2.0.2->modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (54.2.0)
Requirement already satisfied: cython>=0.27.3 in /home/drew/.local/lib/python3.8/site-packages (from pycocotools==2.0.2->modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (0.29.22)
Requirement already satisfied: scipy in /home/drew/.local/lib/python3.8/site-packages (from sk-video==1.1.10->modelplace-api[vis]@ https://github.com/opencv-ai/modelplace-api/archive/v0.4.7.zip->lightweight-openpose==0.2.0) (1.4.1)
Installing collected packages: lightweight-openpose
Successfully installed lightweight-openpose-0.2.0

~/Repositories/oak-model-samples/lightweight_openpose
$ python3 main.py -vid ./demo.mp4
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    main()
  File "main.py", line 13, in main
    inference(model_cls, root_model_path, visualization)
  File "/home/drew/Repositories/oak-model-samples/lightweight_openpose/oak_inference_utils/inference.py", line 59, in inference
    model.model_load()
  File "/home/drew/Repositories/oak-model-samples/lightweight_openpose/oak_inference_utils/base_model.py", line 82, in model_load
    self.create_pipeline(model_blob)
  File "/home/drew/Repositories/oak-model-samples/lightweight_openpose/oak_inference_utils/base_model.py", line 73, in create_pipeline
    self.model_blob.setBlobPath(model_blob)
RuntimeError: BlobReader error: File does not seem to be a supported neural network blob

~/Repositories/oak-model-samples/lightweight_openpose
$ python3 main.py -vid ./demo.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x2570440] moov atom not found

~/Repositories/oak-model-samples/lightweight_openpose
$ python3 main.py -cam
```

**Comment by PVSemk** [comment]
Hello, thank you for your feedback!
It seems like git-lfs connected issue as all videos are stored under git-lfs. Please, check #7

**Comment by AndrewBarfield** [comment]
Works now as expected. Closing the issue.
